# -*- coding: utf-8 -*-
"""lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZu3u8piLgNAOGkqXmJteHBKhXUogIfw
"""

import numpy as np # имортируем библиотеку numpy


matrix = [[1, 2, 5], [3, 1, -2], [0, 6, -4]] # пример матрицы

matrix = np.array(matrix) # переводим матрицу, представленную списком списков чисел, в np.array n*m матрицу

diagonal_sum = matrix.trace() # способ 1: подсчет суммы элементов на главной диагонали с помощью np.trace()
print("Сумма элементов на главной диагонали, извлеченная функцией trace: ", diagonal_sum) # вывод результата

# способ 2: подсчет суммы элементов на главной диагонали с помощью отбора нужных элементов по их индексам с помощью np.arange() и их суммирования с помощью метода np.sum()
shape = min(matrix.shape[0], matrix.shape[1]) # если матрица не квадратная, важно сделать одинаковую индексацию и по столбцам и по строкам, поэтому берем минимальный размер по столбцам и строкам
indexes = np.arange(shape) # получаем вектор индексов, по которым будем доставать элементы на главной диагонали (от 0 до shape)
diagonal_sum = np.sum(matrix[indexes, indexes]) # собираем вектор из элементов на главной диагонали и извлекаем сумму это вектора
print("Сумма элементов на главной диагонали, извлеченная без использования функции trace: ", diagonal_sum) # вывод результата

